# Generated by Django 4.0.5 on 2022-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(blank=True, default=dict, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('parsed', models.BooleanField(default=True)),
                ('parsing_message', models.TextField(default='Parsed Correctly')),
            ],
        ),
    ]
