# Generated by Django 4.0.5 on 2022-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='seqNo',
            field=models.CharField(help_text='Record sequence number', max_length=255, primary_key=True, serialize=False),
        ),
    ]
